<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yuml</string>
	</array>
	<key>name</key>
	<string>yuml</string>
	<key>scopeName</key>
	<string>source.yuml</string>
	<key>uuid</key>
	<string>63173556-52E8-441F-97BE-4CFA08A33BB0</string>
</dict>
</plist>
